- name: Verify all hosts
  hosts: all
  vars_files:
    - ../../vars/main.yml
  tasks:
    - name: Retrieve state of fstab
      command: cat /etc/fstab
      register: fstab_cat_result

    - name: Retrieve state of swap file
      stat:
        get_checksum: false
        path: "{{ server_swap_file_path }}"
      register: swap_file_stat_result

    - name: Run tests
      assert:
        that:
          - fstab_cat_result.stdout is not search(server_swap_file_path|regex_escape)
          - not swap_file_stat_result.stat.exists
